/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

public class App {
    public String  {
        return "Hello World!";
    }

    public static void main()
}
